services:
  postgres:
    image: postgres:latest
    container_name: prova_sergipetec
    restart: always
    environment:
      POSTGRES_DB: provasergipetec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"